---
title: "Assignment 5.2 - Week 9&10 in R"
author: "Aarti Ramani"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
editor_options:
  markdown:
    wrap: sentence
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
#### Load required libraries

```{r LoadLibraries, warning=FALSE, message = FALSE}
library(readxl)
library(ggplot2)    
library(plotly)   
library(dplyr)
```

Read xls into a dataframe

```{r ReadXls, warning=FALSE}
crime_df <- read.csv("C:/Masters/GitHub/Summer2023/DSC640-Data Presentation & Visualization/Week9&10/ex6-2/crimeratesbystate-formatted.csv")
nrow(crime_df)
head(crime_df,5)


education_df <- read.csv("C:/Masters/GitHub/Summer2023/DSC640-Data Presentation & Visualization/Week9&10/ex6-2/education.csv")
nrow(education_df)
head(education_df,5)

```

\newpage
R - Histogram

```{r Histogram, message=FALSE, warning=FALSE}

p <- crime_df %>%
  ggplot( aes(x=murder)) +
    geom_histogram( binwidth=3, fill="#69b3a2", color="#e9ecef", alpha=0.9) +
    ggtitle("R - Histogram for Number of Muders") + 
    theme(plot.title = element_text(size=15))
p 


```

\newpage

R - Box Plot
```{r BoxPlot, message=FALSE, warning=FALSE}

fig <- plot_ly(type = "box", y = crime_df$aggravated_assault, name="Aggravated Assault")
fig <- fig %>% add_trace(y = crime_df$motor_vehicle_theft, name="Motor Vehicle Theft")

fig <- fig %>% layout(title = "R - Boxplot for Aggravated Assault and Motor Vehicle Theft")

fig

```

R - Bullet Chart
```{r BulletChart, message=FALSE, warning=FALSE}
bullet_chart_df = education_df[trimws(education_df$state)== "Arizona",]


fig <- plot_ly() 
fig <- fig %>%
  add_trace(
    type = "indicator",
    mode = "number+gauge+delta",
    value = bullet_chart_df$reading,
    delta = list(reference = 800),
    domain = list(x = c(0.1, 1), y = c(0, 0.1)),
    title =list(text = "Reading"),
    gauge = list(
      shape = "bullet",
      axis = list(range = c(NULL, 800)),
      threshold = list(
        line= list(color = "black", width = 2),
        thickness = 0.75,
        value = bullet_chart_df$reading),
      steps = list(
        list(range = c(0, 250), color = "cornflowerblue"),
        list(range = c(250, 700), color = "lightblue")),
      bar = list(color = "black"))) 

fig <- fig %>%
  add_trace(
    type = "indicator",
    mode = "number+gauge+delta",
    value = bullet_chart_df$writing,
    delta = list(reference = 800),
    domain = list(x = c(0.1, 1), y = c(0.3, 0.4)),
    title = list(text = "Writing"),
    gauge = list(
      shape = "bullet",
      axis = list(range = list(NULL, 800)),
      threshold = list(
        line = list(color = "black", width= 2),
        thickness = 0.75,
        value = bullet_chart_df$writing),
      steps = list(
        list(range = c(0, 250), color = "orange"),
        list(range = c(250, 700), color = "wheat")),
      bar = list(color = "black"))) 

fig <- fig %>%
  add_trace(
    type =  "indicator",
    mode = "number+gauge+delta",
    value = bullet_chart_df$math,
    delta = list(reference = 800 ),
    domain = list(x = c(0.1, 1), y = c(0.6, 0.7)),
    title = list(text = "Math"),
    gauge = list(
      shape = "bullet",
      axis = list(range = list(NULL, 800)),
      threshold = list(
        line = list(color = "black", width = 2),
        thickness = 0.75,
        value = bullet_chart_df$math),
      steps = list(
        list(range = c(0, 250), color = "darkseagreen"),
        list(range = c(250, 700), color = "honeydew")),
      bar = list(color = "black")))

fig <- fig %>% layout(title='R - Bullet Chart')
fig
```
\newpage

R - Additional chart : Funnel Chart
```{r FunnelChart, message=FALSE, warning=FALSE}

#create separate dataframes for reading and writing with the state names. Create lists for corresponding state names for plotting 
#Sort by reading score

reading_df <- education_df %>% group_by(state,reading) %>% count()  %>% arrange(desc(reading))
read_val <- head(reading_df, 5)[["reading"]]
read_state_val <- head(reading_df, 5)[["state"]] #get the top 5 states 
 
writing_df <- education_df %>% group_by(state,writing) %>% count()  %>% arrange(desc(writing))
write_val <- head(writing_df, 5)[["writing"]]
write_state_val <- head(writing_df, 5)[["state"]] #get the top 5 states 
 

fig <- plot_ly(type = "funnelarea", 
    values = read_val, text = read_state_val,
    title = list(position = "top center", text = "Top 5 states with highest reading score",
                 font = list(size = 50)),
    textfont = list(family = "Old Standard TT, serif", size = 13, color = "black"),
    domain = list(x = c(0, 0.4), y =c(0.12, 1))) 


fig <- fig %>% add_trace(
    type = "funnelarea",
    scalegroup = "first",
    values = write_val,text = write_state_val,
    title = list(position = "top left", text = "Top 5 states with highest writing score", 
                 font = list(size = 50)),
    textfont = list(family = "Old Standard TT, serif", size = 13, color = "black"),
    domain = list(x = c(0.6, 1), y = c(0.12, 1)))  


fig
```