---
title: "Assignment 1.2 - Week 1&2 in R"
author: "Aarti Ramani"
date: "2023-06-13" 
output:
    html_document: default
editor_options: 
  markdown: 
    wrap: sentence
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Load required libraries

```{r LoadLibraries}
library(readxl)
library(ggplot2)
library(RColorBrewer)   
library(plotly)
library(webshot)
 
```

#### Read xls into a dataframe

```{r ReadXls}
obama_approvals_df <- read_excel(path = "C:/Masters/GitHub/Summer2023/DSC640-Data Presentation & Visualization/Week1&2/Data/obama-approval-ratings.xls")
nrow(obama_approvals_df)
head(obama_approvals_df,5)
```

### DONUT CHART

```{r DonutChart, message=FALSE, warning=FALSE,fig.width = 8, fig.height = 8}
#fig <- obama_approvals_df %>% plot_ly(labels = ~Issue, values = ~Approve, textposition = 'outside', #textinfo='percent+label', width = 1)
#fig <- fig %>% add_pie(hole = 0.6)
#fig <- fig %>% layout(title = list(text='Donut charts using Plotly'), 
#                      autosize = T ,showlegend = F)
#fig


fig1 <- plot_ly(obama_approvals_df, labels = ~Issue, values = ~Approve, #type = 'pie',
        textposition = 'inside',
        textinfo = 'percent+label',
        text = ~paste(Issue), 
        showlegend = FALSE)
fig1 <- fig1 %>% add_pie(hole = 0.6)
fig1 <- fig1 %>% layout(title = 'Approval Rates by Issue',autosize = T)
fig1
```
### PIE CHART

```{r PieChart, message=FALSE, warning=FALSE}
#Pie Chart
fig <- obama_approvals_df %>% plot_ly(labels = ~Issue, values = ~Disapprove,
                                      type = 'pie', textposition = 'inside', 
                                      textinfo='value+label')
fig <- fig %>% layout(title = "Disapproval Counts per Issue",autosize = T,  showlegend = F) 
fig

```

### STACKED BAR CHART

```{r StackedBarChart}

#Stacked Bar Chart
fig <- plot_ly(obama_approvals_df)
fig <- fig %>% add_trace(x = ~Issue,y = ~None, name = 'None',text = ~None, type='bar',
                         marker = list(color = 'rgb(127, 200, 250)',
                                       line = list(color = 'rgb(8,48,107)' )))
fig <- fig %>% add_trace(x = ~Issue,y = ~Disapprove, name = 'Disapprove',text = ~Disapprove, type='bar',
                         marker = list(color = 'rgb(45, 167, 250)',
                                       line = list(color = 'rgb(8,48,107)')))
fig <- fig %>% add_trace(x = ~Issue,y = ~Approve, name = 'Approve', text = ~Approve, type='bar',
                         marker = list(color = 'rgb(4, 74, 122)',
                                       line = list(color = 'rgb(8,48,107)')))
fig <- fig %>% layout(title = "Approval, Disapproval and Not-Accounted(None) counts by Issue",yaxis = list(title = 'Count'),autosize = T, 
                      barmode = 'stack',xaxis = list(title = "Issue", tickangle = -75))
fig
```

### BAR CHART

```{r BarChart}

#Bar Chart
fig <- plot_ly(obama_approvals_df,x = ~Issue,y = ~Disapprove, name = 'Disapprove',
               text = ~Disapprove, type='bar',
               marker = list(color = 'rgb(20, 71, 252)',
                             line = list(color = 'rgb(8,48,107)'))) 
fig <- fig %>% layout(title="Disapproval counts per Issue",autosize = T,yaxis = list(title = 'Count'),
                      xaxis = list(title = "Issue", tickangle = -75))
fig
```

### LINE CHART

```{r LineChart}
# Line Chart

fig <- plot_ly(obama_approvals_df, x = ~Issue) 
fig <- fig %>% add_lines(y = ~Disapprove, name = "Disapprove")
fig <- fig %>% add_lines(y = ~Approve, name = "Approve") 
fig <- fig %>% layout(title="Approvals and Disapproval by Issue",autosize = T)
fig
```

